# beta.385-realestate.com の server ブロック内に追加する設定例
location = /kouzu {
    return 301 /kouzu/;
}

location /kouzu/ {
    alias /opt/apps/kouzu-reader/;
    index kouzu_reader.html;
    try_files $uri $uri/ /kouzu/kouzu_reader.html;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy same-origin always;
}
